# fly.toml app configuration file generated for tristan-jahnke on 2023-09-19T18:15:25-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "tristan-jahnke"
primary_region = "dfw"
kill_signal = "SIGTERM"
swap_size_mb = 512

[build]

[env]
  PHX_HOST = "tristan-jahnke.fly.dev"
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
  [http_service.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 1000
